* Design
** Agents
*** Card Playing Agent
Selects which card to play against which targets. Short term reward feedback.
*** Card Selection Agent
Selects which cards to add to deck. Long term reward feedback.
*** Potion Agent
Selects when to play potions. Long term reward feedback.
*** Navigation Agent
Selects map movements. Long term reward feedback.
*** Event Agent
Selects event actions. Long term reward feedback.
*** Upgrade Agent
Selects cards to upgrade. Long term reward feedback.
*** Special Agents
Will need one or more additional agents to handle things like card discards, and other special selections, etc.
** Agent coordination
There is a pile of agents. Every agent receives every state. Agents indicate whether they will handle each state. Throw an error if multiple states try to handle the same state.

This allows each agent to be isolated. When playing cards in combat, the card playing agent can step in and say "I got this" then choose the best move. The card playing agent can also keep an eye on all other states in order to determine its own rewards.
* Actions
** DamageAction
Game over
** DiscardAction
Discard one card from hand
** DiscoveryAction
Add one of three random cards to your hand
** GamblingChipAction
Discard any number of cards, then draw that many
** HandCheckAction
Unknown. Do we need to handle this? Appears to be rare.
** NightmareAction
Choose a card to copy
** RetainCardsAction
Cards to retain until next turn
** SetupAction
Put a card from your hand on top of your draw pile. It costs 0 until played.
* Refactor
- [ ] .
- [ ] ├── agent.jl
- [ ] ├── notes.org
- [ ] ├── README.md
- [X] ├── relay.jl
- [ ] ├── src
- [X] │   ├── Encoders.jl
- [X] │   ├── Networks.jl
- [X] │   ├── SARSM.jl
- [ ] │   ├── STSAgents.jl
- [X] │   └── Utils.jl
- [X] └── test
- [X]     ├── Encoders.jl
- [X]     ├── Networks.jl
- [X]     ├── runtests.jl
- [X]     ├── SARSM.jl
- [X]     └── Utils.jl
