* Design
** Agents
*** Combat agents
**** Card playing agent
This agent answers one or two questions:

1. What card or potion should I play?
2. What target should I play the card/potion against?

Not all cards/potions have targets, so the second question will not always need to be answered.
***** Receives / State
- Encoded draw pile
- Encoded discard pile
- Hand details, zero padded, shuffled, all cards (not just playable cards)
- Monster details, zero padded, shuffled
- Player details
- One-hot encoded potions
****** Hand card details
- One-hot encoded card
- Cost
- Upgrades
****** Monster details
- Encoded monster powers
- Move hits, hit damage, total damage
- Block
- Current HP, max HP, HP ratio (current HP / max HP)
******* Monster power details
- One-hot encoded power category / id
- Power amount
****** Player details
- Current HP, max HP, HP ratio (current HP / max HP)
- Encoded player powers
******* Player power details
- One-hot encoded power category / id
- Power amount
****** Encoded draw and discard piles
- One-hot encoded card category / id
- Mean-hot encoded card upgrades
***** Outputs / Action
- Card/potion weights
- Target weights

The applicable weights will be run though a softmax function to give the final percentages for the playable actions.
***** Training / Reward
Reward is amount of HP lost.
**** Card weight override agent
Receives: relics, potions, cards in hand, cards in draw pile, cards in discard pile, player state, enemy states
Receives: card selected for playing and stats about that card
Outputs: an override probability for the card selected for playing

This allows us to handle cases where the cards cost is changed, as with Sneko Eye and other special cases.
*** Other agents
**** Card selection agent
Receives: relics, potions, cards in deck, player stats, floor, gold, available cards
Outputs: weights for available cards, weight for skip

This allows us to pick cards and build our deck.
**** Event agent
**** Map agent
